### ISSUE TITLE
Add Mac Studio support

### ISSUE THREAD

**Issue by staze** [MLBZ521/MacAdmin#15]
Get-LatestOSSupported.sh throws a "Model No Longer Supported" for the Mac Studio. Machine shows up as being "Mac13,1" (at least).

**Comment by MLBZ521** [comment]
@staze Sorry for the delay on this.

While the Mac Studio isn't technically "supported" in the script, this shouldn't happen on the latest version of the script.  It specifically will just assume any `$unknown_model` that's released going forward will support the `$latest_OS`.

I can confirm in my environment that `Mac13,1`'s report Monterey as expected.

**Comment by staze** [comment]
Can confirm. I had grabbed the latest version when I submitted this, and apparently forgot to confirm it wasn't working. 

Thank you sir!

**Comment by MLBZ521** [comment]
No worries!
