### ISSUE TITLE
Get-LatestOSSupported.sh

### ISSUE THREAD

**Issue by zimbomb** [MLBZ521/MacAdmin#20]
what would cause multiple machine return <result>Current OS Not Supported. I have several newer machine with this issue. When looking at the model identifier I have some that return Ventura* and other with the Not supported. Any help would be appreciated.

**Comment by MLBZ521** [comment]
@zimbomb I'd imagine you have to be running the latest revision of the script to have any results of `Ventura*`, but just want to confirm.

What hardware models are reporting `Current OS Not Supported`?  Please provide the Model Identifiers.  I can't really help further without that info as I haven't noticed this in my environment and no one else has reported this issue (in my environment or publicly).

**Comment by zimbomb** [comment]
i am not sure what happened, but now there are about 11 machines that have
the return of current not supported. At this point I will blame it on my
implementation.

**Comment by MLBZ521** [comment]
@zimbomb Ok.  Feel free to re-open this issue if this happens again and include the Model Identifiers and the current OS version the devices are running.

Thanks
