### ISSUE TITLE
expectedCSCustomerID is not working

### ISSUE THREAD

**Issue by fcerullo-kitman** [MLBZ521/MacAdmin#23]
Hi

Can you please describe the format type for expectedCSCustomerID in the code?

I've tried double quotes using the Customer ID available in the Crowdstrike Console and it always return "Invalid Customer ID"

Thanks
Fabio

**Comment by MLBZ521** [comment]
@fcerullo-kitman Sorry for the delay.

It should be in a UUID format, as the example CID in the code:
  * `expectedCSCustomerID="12345678-90AB-CDEF-1234-567890ABCDEF"`

It's not the same format used when licensing the sensor.

You can get it with this one-liner:
  * `/usr/libexec/PlistBuddy -c "Print agent_info:customerID" /dev/stdin <<< $( sudo /Applications/Falcon.app/Contents/Resources/falconctl stats agent_info --plist )`

**Comment by fcerullo-kitman** [comment]
That did the trick, thanks! It is a great script to verify everything is in order with the Crowdstrike deployment.

**Comment by MLBZ521** [comment]
Great!  Glad that worked and is helpful for you.
