### ISSUE TITLE
Check for running OS greater than supported OS might be using wrong comparator

### ISSUE THREAD

**Issue by tantonw** [MLBZ521/MacAdmin#26]
https://github.com/MLBZ521/MacAdmin/blob/06319b803faaae4d256fdcc64d8bfe70f341e93e/Jamf%20Pro/Extension%20Attributes/Get-LatestOSSupported.sh#L484

I think this comparison should be strictly ">" rather than ">="

**Comment by MLBZ521** [comment]
@tantonw Hey, thanks for the catch!  This has been fixed in v2.5.3 7bfb463.
