### ISSUE TITLE
Apple just moved the ball on Sequoia

### ISSUE THREAD

**Issue by staze** [MLBZ521/MacAdmin#28]
Apple just updated Sequoia hardware requirements to have Air's be 2020 or later. 

https://www.apple.com/macos/macos-sequoia-preview/ 

Yesterday it was 2018 or later...

**Comment by staze** [comment]
might be false alarm. macworld article appears to be wrong... https://www.macrumors.com/2024/06/10/macos-sequoia-and-ipados-18-compatibility/

so script looks correct based on what I'm reading.

**Comment by staze** [comment]
closing

**Comment by MLBZ521** [comment]
Yeah, I updated the script yesterday for Sequoia.

Thanks

**Comment by staze** [comment]
yeah, saw that. Someone pointed out lack of 2018/2019 air's on sequoia, which I swear were there yesterday, but now aren't... seems like Macworld is just wrong though.

**Comment by MLBZ521** [comment]
That's correct, 2018 and 2019 MacBook Airs do not support Sequoia, [per Apple](https://www.apple.com/macos/macos-sequoia-preview/).  Those are the only Macs that were dropped.  Only 2020 MacBook Airs and newer are supported.  MacRumors link you shared looks correct to me.
