### ISSUE TITLE
MacAdmin/Apple_RepairPrograms.py /

### ISSUE THREAD

**Issue by mani2care** [MLBZ521/MacAdmin#6]
MacAdmin/Apple_RepairPrograms.py /
 
not working as on date 

geting error 

 ~/Desktop/Apple_RepairPrograms.py 
usage: Apple_RepairPrograms.py [-h] [--serialnumber C02LA1K9G7DM]
                               [--model MacBookPro11,4]
                               [--input /path/to/input_file.csv]
                               [--output /path/to/output_file.csv]

Apple Exchange and Repair Extension Programs Lookup

optional arguments:
  -h, --help            show this help message and exit

Single Device:
  --serialnumber K9G7DM, -s 1K9G7DM
                        A single serial number
  --model MacBookPro11,4, -m MacBookPro11,4
                        A model or model identifier. Example: MacBook Pro
                        (Retina, 15-inch, Mid 2015) or 15-inch Retina MacBook
                        Pro (Mid 2015) or MacBookPro11,4

Batch Process:
  --input /path/to/input_file.csv, -i /path/to/input_file.csv
                        Path to a CSV with a list of serial numbers, and
                        models or model identifiers. Example: MacBook Pro
                        (Retina, 15-inch, Mid 2015) or 15-inch Retina MacBook
                        Pro (Mid 2015) or MacBookPro11,4
  --output /path/to/output_file.csv, -o /path/to/output_file.csv
                        Path to a CSV where devices that are eligible for a
                        repair will be written. WARNING: If the files exists,
                        it will be overwritten!

Error:  Not enough arguments provided.
NTS-IT-001:Desktop manikandan.raju$

**Comment by MLBZ521** [comment]
@mani2care I've made an update (v1.1.0) to this [script](https://github.com/MLBZ521/MacAdmin/blob/master/Apple_RepairPrograms.py) since you submitted this issue, are you still seeing this error?

If you can provide the exact arguments you provided to the script that may help.  You can redact any sensitive information, such as serial numbers.

**Comment by MLBZ521** [comment]
Feel free to re-open this issue if you're still experiencing it.
