### ISSUE TITLE
CrowdStrike Status

### ISSUE THREAD

**Issue by seanism** [MLBZ521/MacAdmin#8]
Thank you for creating these extension attributes.  For the CrowdStrike status I keep getting invalid customer ID.  Do I use the checksum on the download page?  Or is there another code I should use?

**Comment by MLBZ521** [comment]
@seanism Hello Sean, sorry, I didn't get a notification about this issue.

You'll need to enter your CID into the script so that it can verify it against what the Agent is configured with.

Let me know if you have any other questions.  (You can @me if you like.)

**Comment by MLBZ521** [comment]
Feel free to let me know if you have any further questions.
