### ISSUE TITLE
Incorrect OS Limitations reported in jamf_ea_LatestOSSupported.sh

### ISSUE THREAD

**Issue by rougegoat** [MLBZ521/MacAdmin#9]
Using the 1.11.0c version of this extension, we're seeing a large number of macs currently on macOS 11 report that "Mojave / OS Limitation" is their latest supported OS.  Machines we have been able to identify appear to primarily be iMac15,1.  We're still investigating if other models are reporting inaccurately.

**Comment by MLBZ521** [comment]
Hello @rougegoat, sorry, I didn't get a notification about this issue.

I missed a couple hardware models with Monterey, not really sure what happened this go around.  Either way, this has been fixed with 15656e6.

Thanks for the FYI!
